"""Sprint 2: movimientos de inventario

Revision ID: 87f7549a6b65
Revises: 931bf2245183
Create Date: 2026-08-28 22:28:33.345813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f7549a6b65'
down_revision = '931bf2245183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_resultante', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_alimento_id'), ['alimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimientos_fecha'))
        batch_op.drop_index(batch_op.f('ix_movimientos_alimento_id'))

    op.drop_table('movimientos')
    # ### end Alembic commands ###
