"""Sprint 6: notificaciones leidas

Revision ID: 8e04164a2ab3
Revises: 87f7549a6b65
Create Date: 2026-08-29 13:02:32.313828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e04164a2ab3'
down_revision = '87f7549a6b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones_leidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('leida_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tipo', 'referencia_id', name='uq_notificacion_leida')
    )
    with op.batch_alter_table('notificaciones_leidas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_leidas_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones_leidas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_leidas_usuario_id'))

    op.drop_table('notificaciones_leidas')
    # ### end Alembic commands ###
