"""Migracion inicial: usuarios y alimentos

Revision ID: d82d532e667e
Revises: 
Create Date: 2026-08-27 22:18:33.103914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82d532e667e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('unidad_medida', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alimentos_codigo'), ['codigo'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('ultima_sesion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_usuario'), ['usuario'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_usuario'))

    op.drop_table('usuarios')
    with op.batch_alter_table('alimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alimentos_codigo'))

    op.drop_table('alimentos')
    # ### end Alembic commands ###
